rss_url: 'http://qiita.com/tags/%E8%87%AA%E4%BD%9C%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89/feed.atom'
where_to: 'https://discord.com/api/webhooks/747110604858196010/5PkYVVvoLLPRU4qMT4Eet-q4IXAUwxp_fmAbpTseceR36nLtdaT0JZdxxbM2jkMm3xBC'

